version: "3.7"
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
      volumes:
      - ./:/app
    image: builder:latest
    command: bash -c "cd /app && git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git && cd boxfuse-sample-java-war-hello && mvn clean package -Dmaven.test.skip=true"